name: hwctl
version: 0.1.0.0
synopsis: Admin CLI for hello-work-software-jobs
license: BSD-3-Clause

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - dotenv
  - modern-uri
  - optparse-applicative
  - prettyprinter
  - process
  - req
  - temporary
  - text
  - transformers

executables:
  hwctl:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hwctl
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

library:
  source-dirs: src

tests:
  hwctl-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hwctl
