resolver: lts-24.11

system-ghc: true
install-ghc: false

packages:
  - .

extra-deps:
  - dotenv-0.12.0.0@sha256:2f25615cec37ff9a66a48ef0ebf2ac96ae989911d0c26c6796fc2f5247bdd665,4702

allow-newer: true
allow-newer-deps:
  - dotenv
