import type { Metadata } from "next";
import "@/styles/globals.css";
import { Provider } from "jotai";
import { Navbar } from "@/components/ui/Navbar";
import layoutStyles from "./Layout.module.css";

export const metadata: Metadata = {
  title: "ハローワーク求人情報検索",
  description: "Generated by create next app",
};

const navItems = [{ label: "お気に入り一覧", href: "/favorites" }];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Provider>
          <div className={layoutStyles.wrapper}>
            <Navbar brand="ハローワーク求人情報検索" items={navItems} />
            <main className={layoutStyles.main}>{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
