import type { Metadata } from "next";
import "./styles/globals.css";
import { Provider } from "jotai";
import { NavHeader } from "./_components/NavHeader";
import layoutStyles from "./Layout.module.css";
export const metadata: Metadata = {
  title: "ハローワーク求人情報検索",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Provider>
          <div className={layoutStyles.wrapper}>
            <header className={`${layoutStyles.header} ${layoutStyles["header-title"]} ${layoutStyles["header-title--primary"]}`}>
              <h1>ハローワーク求人情報検索</h1>
              <NavHeader />
            </header>
            <main className={layoutStyles.main}>{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
